name: Fetch and Update Worker

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  fetch-worker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main  # 明确指定分支
        
    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Download _worker.js
      run: |
        echo "当前工作目录: $(pwd)"
        echo "目录内容:"
        ls -la
        
        # 下载文件
        curl -s -L -f -o _worker.js \
          "https://raw.githubusercontent.com/byJoey/cfnew/refs/heads/main/%E5%B0%91%E5%B9%B4%E4%BD%A0%E7%9B%B8%E4%BF%A1%E5%85%89%E5%90%97"
        
        echo "下载后目录内容:"
        ls -la
        echo "_worker.js 文件内容预览:"
        head -n 5 _worker.js || echo "文件为空或不存在"
        
    - name: Commit and push
      run: |
        echo "Git 状态:"
        git status
        
        # 强制添加文件并提交
        git add -f _worker.js
        
        if git diff --staged --quiet; then
          echo "没有变化需要提交"
        else
          git commit -m "🤖 Auto-update _worker.js [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push origin main
          echo "✅ 文件已提交并推送到 main 分支"
        fi
